name: Build and deploy MkDocs site

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MkDocs
        run: pip install mkdocs mkdocs-awesome-pages-plugin mkdocs-material mkdocs-minify-plugin

      - name: Build MkDocs site
        run: mkdocs build --config-file mkdocs/mkdocs.yml

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --site-dir docs/site/ --remote-branch gh-pages
