name: Build and deploy MkDocs site

on:
  push:
    branches:
      - docs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'docs'

      - name: Install MkDocs
        run: pip install mkdocs mkdocs-awesome-pages-plugin mkdocs-material mkdocs-minify-plugin

      - name: Build MkDocs site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
