services:
  mkdocs:
    build: .
    image: python-vimeo-utils_mkdocs
    container_name: python-vimeo-utils_mkdocs
    ports:
      - "8989:8989"
    volumes:
      - .:/docs
    command: serve --dev-addr=0.0.0.0:8989
    restart: always
